### ISSUE TITLE
[Bug]: version 0.3.0 broken on windows

### ISSUE THREAD

**Issue by racinmat** [avast/wanna-ml#110]
### What happened?

module posix is used even on windows, although it's not present on windows, so it crashes

### wanna.yaml file

```yaml
does not matter
```

### wanna-ml CLI command

```shell
wanna notebook create --name wanna-hmic-matej --version matej --profile hmic-ai-test
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\e10270\.local\bin\wanna.exe\__main__.py", line 4, in <module>
  File "C:\Users\E10270\AppData\Local\pipx\pipx\venvs\wanna-ml\Lib\site-packages\wanna\cli\__main__.py", line 10, in <module>
    from .plugins.runner import PluginRunner
  File "C:\Users\E10270\AppData\Local\pipx\pipx\venvs\wanna-ml\Lib\site-packages\wanna\cli\plugins\runner.py", line 4, in <module>
    from wanna.cli.plugins.job_plugin import JobPlugin
  File "C:\Users\E10270\AppData\Local\pipx\pipx\venvs\wanna-ml\Lib\site-packages\wanna\cli\plugins\job_plugin.py", line 16, in <module>
    from wanna.core.services.jobs import JobService
  File "C:\Users\E10270\AppData\Local\pipx\pipx\venvs\wanna-ml\Lib\site-packages\wanna\core\services\jobs.py", line 38, in <module>
    from wanna.core.services.docker import DockerService
  File "C:\Users\E10270\AppData\Local\pipx\pipx\venvs\wanna-ml\Lib\site-packages\wanna\core\services\docker.py", line 7, in <module>
    from dirhash import dirhash
  File "C:\Users\E10270\AppData\Local\pipx\pipx\venvs\wanna-ml\Lib\site-packages\dirhash\__init__.py", line 13, in <module>
    from scantree import (
  File "C:\Users\E10270\AppData\Local\pipx\pipx\venvs\wanna-ml\Lib\site-packages\scantree\__init__.py", line 3, in <module>
    from ._path import (
  File "C:\Users\E10270\AppData\Local\pipx\pipx\venvs\wanna-ml\Lib\site-packages\scantree\_path.py", line 6, in <module>
    from posix import DirEntry
ModuleNotFoundError: No module named 'posix'

```
```

**Comment by racinmat** [comment]
correction: even wanna-ml 0.2.37 is broken on windows if I install it to the new environment. 
In fact, scantree==0.0.2 breaks it. Scantree==0.0.1 makes it work. Commented here https://github.com/andhus/scantree/issues/4
